### ISSUE TITLE
Desktop: Small fixes for BETA

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1642]
- [x] Launcher: Allow to change installation directory
- [x] Launcher: BETA disclaimer
- [x] Launcher: Windows OS systray icon should be colored
- [x] Launcher: Close button should close the app
- [x] Launcher: Uninstall should clean the cache
- [x] Explorer Desktop: New default settings: Ultra, radius 6, full screen borderless (#1639)
- [x] Explorer Desktop: Hide `auto-quality` setting (#1639)
- [x] Explorer Desktop: Timeout error should appear on every loading screen and not just the first one (#1640)
- [x] ~Explorer Desktop: Reload the App should maintain the WebSocket communication~ Remove Reload button
- [x] Kernel: Don't reload the website when it is in error state
- [x] Launcher: Center loading icon
- [x] Launcher: Minimum size to resize
- [x] Explorer Desktop: Show `EXIT` button in ProfileHUDDesktop for Guests. (#1642)
- [x] Explorer Desktop: Sometimes `EXIT` button doesn't work (#1642)
- [x] Explorer Desktop: Desktop settings are not being seen since the new full screen UI
- [x] Explorer Desktop: /SHOWFPS not working correctly
- [x] Explorer Desktop: Enter as a guest sometimes skip the avatar editor and join with `soporote` nickname
- [x] Launcher: Increment minimum window size 
- [x] Explorer Desktop: Sign in not working
- [x] Explorer Desktop: /SHOWFPS show REALM, ISLAND (#1680)

**Comment by olavra** [comment]
https://docs.google.com/document/d/1RGx1uiVzJpgzdNVygW-IMRBPNR0cuI5ETaJHWXqPEKQ/edit

**Comment by lorux0** [comment]
scene load radius remains at 4 due parcel loading delays and instability

**Comment by kuruk-mm** [comment]
All tasks done
