### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#226]
- [ ]  Port kernel dist to local static web server instead of remote kernel
- [ ] Put a guide in the PRs so that in case there is a PR in `unity-renderer`, the pipeline of` explorer-desktop` must be re-executed after the PR of `unity-renderer` is merged (thus the PR of `explorer-desktop` uses` master` of `unity-renderer` in the future this will be automated)
- [ ] Electron launcher that updates `unity-renderer` entirely
- [ ]  Chromium headless (maybe use PuppeterSharp?)
- [ ]  Wallet Connect
- [ ]  Window Mode
- [ ]  Error Screen Port
