### ISSUE TITLE
Optimize the load of wearables on the backpack

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2325]
If a user has a high amount of wearables or a third party collection has lots of wearables, there is a very noticeable hiccup when loading them. In order to solve this issue we need to support throttling and third party wearables pagination.

## DONE

- [x] Throttling: load a max of 10 wearables per frame
- [x] Add pagination for current collection wearables

## BUGS

- [x] Fix equipped wearables to be selected when the page changes
- [x] Fix item toggles being turned off if the wearable is not available for the current avatar ( Male/Female )
- [x] Research if it's possible to use only 1 prefab instead of one per rarity ( using skins as scriptable objects ) 
- [x] Fix Stress-test issues, some thumbnails fail to load or end up blank for ever

## TODO

- [x] Fix Tests

**Comment by Kinerius** [comment]
Current state of the pagination, there's still an issue with forgotten texture promises that are being re-downloaded every time.

https://user-images.githubusercontent.com/7646450/182484944-e44d9af0-7933-405a-a991-1c1688cda566.mp4
