### ISSUE TITLE
Release Mac Client

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2437]
- [x] decentraland/unity-renderer#1000
- [x] decentraland/unity-renderer#1050
- [x] decentraland/unity-renderer#1698
- [x] decentraland/explorer-desktop#29
- [x] decentraland/explorer-desktop#128
- [x] decentraland/explorer-desktop#194
- [x] decentraland/explorer-desktop#287

**Comment by xavi-dcl** [comment]
Closing this Epic since no tickets reference it and its checklist seems to be completed. FYI @aixaCode
