### ISSUE TITLE
Implement tracking events for login funnel

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2864]
The growth team is trying to get some more insights into the login funnel, and we are trying to add some more steps in addition to the existing ones. We want to add the following steps:
Avatar Creation Loaded -> There's no event triggered for the avatar creation screen showing up
Name Creation Loaded -> avatar_edit_success is triggered after clicking (Done)
ToS Loaded -> No event is generated here
ToS Accepted -> lifecycle event with stage  loading_7_load_scenes is triggered after accepting ToS

**Acceptance criteria:**

- [x] Implement Avatar Creation event
- [x] Implement Tos Accepted event
- [ ] Update tracking documentation according to these changes
