### ISSUE TITLE
Channel refinement iteration 3

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#2939]
- [x] We are not limiting the amount of channels that a player can join and create. We have to display the corresponding message for each case []([A](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3167%3A22033)) or [B](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3167%3A24291)

### **Design**
**Conversations list View**
- [x] The separators channels and private conversation background container must be white instead of grey.
- [x] Make more room between the spinner and both separators. Now they make me feel claustrophobic.
![Screenshot 2022-09-01 at 16.15.44.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/e3a10704-3f1d-4a04-b902-af6b0affaf69)
![Screenshot 2022-09-02 at 10.30.06.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/8f07926a-156f-4e11-8891-eff202eb3159)

**Browse channels**
[Use this Figma link for reference](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3420%3A34530)

- [x] Increase the gap between the buttons `create` and close button. Center in Y the icon and the text. 
- [x] While the channels are loading the message `Use the search bar (...)` shouldn't be shown.
![Screenshot 2022-08-30 at 11.34.44.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/24adadc5-43ff-42ff-858f-77b72ba719a2)
- [x] The search is not working as expected. There are 2 different instances that can not co-exist at the same time: the `Did you mean?` and `No results`. 
- [x] Increase the size of `no results` title and the text box of the description. Add the line  `If the channel doesn't exist make it happen!` 
- [x] Fix the `create channel` container size. The color must be #FF2D55.
- [x] In the `Did you mean` instance replace the `use the search bar (...)` message for `If the channel doesn't exist make it happen!` and add the `Create channel `button.
- [x] In the channel row the text `joined` the color must be #34CE76 and the font semi bold.

**Create channel modal**
- [x] The color of the modal container must be #ECEBED instead of white.
- [x] I had to make some adjustments in the title of the input. Put the `asterisk` ahead `name`. Remove the brackets from `required` and set the font regular.
- [x] The input container must be #FFFFFF instead of white grey. Its grey outline #CFCDD4 is missing.
- [x] The `X` button to clean the input is missing.
- [x] Feedback when a channel can't be created because the name has spaces is missing. Let's put `Spaces not allowed`
- [x] The feedback `Name already taken` is exclusive when a user wants to name her channel nearby. For the rest we must show [this](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2877%3A19296). If the user clicks `here` she is taken & joined directly to the channel.

**Modals**

- [x] The modal implementation to join a channel doesn't correspond with the original design. Use as reference the modal to leave a channel that is right.

**Channels members**
- [x] Increase search bar and players row width to make it match with the original design. Reference [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS?node-id=3496:24750#263186416).
- [x] Decrease avatars and players' names size, must be the same than the chat messages in this case. Then decrease the player row height.
- [x] The color outline of the avatar snapshot must be #D0CED3
- [x] The notifications and members icon must be a bit smaller. Then correct the space between the nav bar buttons. Reference [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS?node-id=3496:24750#263185990).
- [x] Align visually in the center the magnifier icon with the avatars snapshots. Reference [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS?node-id=3496:24750#263190711).
- [x] When using the scroll bar in the members list the panel closes automatically. I record [this](https://drive.google.com/file/d/1p3kFJnjZ6x7Y9bRutqz2q-x8CVlVsOSu/view?usp=sharing) video so you can see it.
- [x] Here is the right texture which is `RectRadius12`. This overlapping between textures in the fade animation should not be noticed.
![Screenshot 2022-09-09 at 10.40.40.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/bf1c6586-765e-4181-b01f-25fd2d3d9cbd)
