### ISSUE TITLE
Check memory consumption and leaks

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3068]
A user from the `ext-onginnovations` reported that he noticed that the graphics memory wasn't going down when unloading scenes, it's been a while since we did our last memory profiling.

- [x] Set Scene Load Radius to 1,
- [x] Do a memory profile at genesis plaza, go to an empty scene then go back to genesis plaza and do another memory profile.
- [x] Compare the first and second memory profiles in search of a leak using the memory profiler tool.
- [x] Check the first memory profile and analyze its usage,

**Comment by xavi-dcl** [comment]
@Kinerius is this still relevant? Idk if we have been profiling & fixing leaks recently, or if doing so can help make the web client crash less often?

**Comment by Kinerius** [comment]
We still have some leaks but they are quite small, I don't recall any fix recently, this is still relevant
