### ISSUE TITLE
Reduce size of MainScripts assembly

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#3150]
## Problem Statement
Having a big `MainScripts` assembly forces us to couple code--decoupling is difficult because moving code to new assemblies lead to cyclic reference issues. Also, when any assembly is big enough, compilation times are increased, lowering the development productivity.

### Actionables
- [ ] Move all SDK component implementation to their own assembly
- [ ] Encapsulate SDK component factory into its own assembly, this assembly will reference all the component assemblies
- [ ] Now, `MainScripts` can just reference the component factory and most of the references should be ready to be removed
