### ISSUE TITLE
[Standalone AB Converter] Fix old Bugs

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3505]
We have to check if old bugs are still happening on this new repo:

- [x] https://github.com/decentraland/asset-bundle-converter/issues/1 (Done)
- [x] https://github.com/decentraland/asset-bundle-converter/issues/2 (Done)
- [x] https://github.com/decentraland/asset-bundle-converter/issues/3 ( building doesn't exist anymore? )
- [x] https://github.com/decentraland/asset-bundle-converter/issues/4 ( cant convert just assets )
- [x] https://github.com/decentraland/asset-bundle-converter/issues/5 ( Lacks Info )
- [x] https://github.com/decentraland/asset-bundle-converter/issues/6 (Tests are not on explorer anymore)
- [x] https://github.com/decentraland/asset-bundle-converter/issues/7 ( This is not a bug but a nice to have feature )
- [x] https://github.com/decentraland/asset-bundle-converter/issues/8 (Scenes convert ok)
