### ISSUE TITLE
Arrange file/type layout and include it in CodeCleanup

### ISSUE THREAD

**Issue by popuz** [decentraland/unity-renderer#3522]
# Description
We need to enforce our ordering code style. Unfortunately,` .editorconfig` doesn't provide settings for that. However, there is a possible solution with [file and type layout patterns](https://www.jetbrains.com/help/resharper/2022.2/File_and_Type_Layout.html). Such defined layout can be used in the Cleanup Code run to re-arrange blocks.

# Tasks
- [ ] Create layout that would reflect our code style guideline.  
- [ ] include this layout in Cleanup Code profile (and check that it arranges blocks properly)
- [ ] research, if there is a possibility to include it in Inspect Code run
