### ISSUE TITLE
Players in Worlds can Chat with Friends and Channels

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3551]
### Description:
During this first public phase, many functionalities will remain intact and homogeneous between worlds. Players will be able to experience the scenes using their avatar as usual, **continue chatting in public channels and private conversations**, maintain their settings, and their inventory configuration.

### Task Breakdown:
- [ ] Refinement to add identified tasks + estimation for everything 

### Acceptance Criteria:
- [ ] Players can use the nearby chat as usual
- [ ] Players can chat with their Friends as usual
- [ ] Players can use Channels as usual

**Comment by dalkia** [comment]
Closing since this task is already complete.
