### ISSUE TITLE
ProfileHUD needs an Interface and fire Events.

### ISSUE THREAD

**Issue by PalauiDCL** [decentraland/unity-renderer#3704]
## Interface

ProfileHUD does not implement an interface and that does not allow to switch between different UI or change versions easily, creating one would solve this issues.

---

## Observer pattern

Currently the ProfileHUD Controller is accessing members from the view that should be private and subscribes to their buttons without the view knowing. a series of events should be created in the interface to be fired when those buttons are pressed and the controller shoulb subscribe to them.

---

## Subtasks

* [x] Create the IProfileHUD interface
* [x] Create the needed events for all the buttons
* [x] Decide the methods that must be implemented by the interface and the ones that belong only to this specific view.
* [x] Implement interface in the new ProfileHUD
* [x] Implement interface in the old ProfileHUD
* [x] Update the tests so they use the interface
* [x] Update all needed UI so it uses the interface and not the class
* [x] Feature Flag
