### ISSUE TITLE
New passport 2nd polish round

### ISSUE THREAD

**Issue by davidejensen** [decentraland/unity-renderer#3782]
In order to simplify the refinement of the passport and to introduce new changes to its design, the refinement has been split in multiple parts, to also simplify the iteration and avoid big PRs.

### Requirements
**Davide**
- [x] Add links when present in passport (waiting for Marc's PR)
- [x] Add popup on link press
- [x] Scale the passport to make it a bit smaller (review with Alvaro)
- [x] Remove name and separator from the context menu
- [x] Add # back in the names
- [x] Empty links should hide the relative section
- [x] Teleport should close passport
- [x] Closing passport shouldn't lock the mouse
- [x] Black overlay is reacting to the passport scale when it shouldn’t
- [x] Copy name/address toast: if they are triggered in passport A and haven't disappeared before I close it and then I go and open passport B they are shown again there when I haven't clicked the copy buttons.
- [x] The ProfileHUD button is not behind the passport black overlay
- [x] Passport scale is not working horizontally
- [x] Implement new intro empty status. The icon is already in the project and is called `IntroIcon`. Figma [here](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=2045%3A6716&t=RNw0CyugZliKUygo-1)
- [x] Add icons to every category empty state in the collectibles sections. Assets are already imported `EmotesIcon` `NameIcon` `WearablesIcon`. Figma reference [here](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=2443%3A6572&t=RNw0CyugZliKUygo-1)
- [x] From now on the `NoWearables` state must look like [this](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=2365%3A5421&t=RNw0CyugZliKUygo-1). 
- [x] Show connect wallet popup if guest
- [x] ~Remove character preview outline glitch~ Will be solved with #3675
- [x] The text in the orange button (selected section) must be white.
- [x] Add animation for panel show/hide
- [x] `Name copied! `feedback should be center on the X axis with the name copy button which position is dynamic.
- [x] Collectibles section: arrows buttons should be visible every time I'm in the row area. Now is very hard to click them because they disappear as soon as I'm not hovering an item.
- [x] Collectible section: first NFT item must be aligned on the left with its title. Regarding the right, the gap must be the same. Use the intro card as reference.
- [x] Increase size of the carousel dots.
- [x] Fix chat button position. Must be closer to the menu button if the jump in doesn't exist. Check it [here]
- [x] Replace empty state on the intro description by `No intro description.`. Font regular text color **#716B7C**
- [x] Add `Name copied!` or `Address copied` after pressing the copy button. Alignment criteria: on top, centred regarding the copy icon. [Figma link](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=1258%3A95826&t=eC9SMwnNTKI8Z5op-1)(https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=2045%3A6716&t=eC9SMwnNTKI8Z5op-1).
- [x] Fix bottom left rounded corner.
- [x] On hover, every wearable card must increase its scale. If it's and NFT we must add the rainbow animated outline.
(https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Ex-Passport-%2F-Profile?node-id=1960%3A14534&t=eC9SMwnNTKI8Z5op-1).
- [x] Fix navigation bar and add it's white background when UI overlaps behind after using the vertical scroll.
- [x] Show white close button in guests's passport.
- [x] Add fade in/out animation to the 360 toast.
- [x] Add fade in/out animation to the chat toast. 
- [x] Close the chat toast if it's opened when clicking the context menu.
- [x] Increase the vertical gap between the chat toast and the chat button.
- [x] Remove `blocked` status from friends button and implement the new design.
- [ ] #3858
- [x] Carrousel arrows must be shown just if there is more than 1 page and when the user muse hover the row. 
- [x] If the context menu is opened, clicking again on it's button should close it.
- [x] ~Online/offline status is missing.~
- [x] Move the avatar model a bit more down.
- [x] Equipped wearables show per row must be 5, not 6.
- [x] Fix items thumbnails masks. Some corner are visible outside the white container.
- [x] Don't save the previous status once open a passport back.

**Romi**
- [ ] Add a black gradient bellow the PlayerInfo
- [x] Turn off the name from the context menu
- [x] Horizontal alignment in general needs a review.
- [x] Add icons to intro, and collectibles categories empty status.
- [x] Remove price icon.
- [x] Fix tab section x alignment.
- [x] Fix NFTs colours and icons.
- [x] Add missing shadow to the intro panel.
- [x] Add avatar shadow
- [x] Fix emotes/werables empty messages vertical alignment.
- [x] Add scale animation on hover to every button.
- [x] Add missing shadow to NFTs.
- [x] Guest's close button must be white.
- [x] Replace empty states text color for #716B7C instead of black.
- [x] Fix carrousel arrow's color and add their containers.
- [x] Fix guest UI view.
- [x] Fix blocked UI view.
- [x] Guest image quality is poor.
- [x] Design new blocked player status.
- [x] Fix feedback when hovering the copy button: apply it on the icon, not in the name or addresses.
- [x] Increase size of both copy icons.
- [x] All the buttons must have a hover animation. [Here](https://www.figma.com/file/HEjNjFOQUcCgLK3lDMFrw5/DCL-Design-System-%26-Guidelines?node-id=359%3A368&t=Yqk4VzlefMFoSshf-1) are the color guidelines. The close button container will be an exception considering it has transparency.
- [x] Fix context menu position in relation with its button. Link [here]
- [x] Fix avatar background color.
- [x] Names and address horizontal layout not working properly.
- [x] Unblock button colors are wrong.
- [x] User's names are always semi-bold and white. If they have `#y7jl` its color is grey and in regular.

**Comment by davidejensen** [comment]
Online offline status is going to be disabled untill dServices doesn't allow the retrival of the status for non friends
