### ISSUE TITLE
Integrate Lambdas into Renderer Iteration #2

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#3839]
The principal scheme: https://miro.com/app/board/uXjVP2qlQGQ=/ 

### Acceptance Criteria:

- [ ] Refactor `Emotes Catalog Service` to use `Lambdas Service` and provide backward compatibility with Kernel
- [ ] Refactor `Catalog` to comply with `Emotes Catalog Service`'s way of doing things and provide backward compatibility with Kernel
- [ ] Migrate Profiles to `lamd2`
- [ ] Integrate the corresponding APIs to Extended Passport

TODO: create tasks
