### ISSUE TITLE
BuilderInWorld UI Feedback Subtask

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#87]
- [x] Change smart items catalog background for a purple color like the builder

- [x] Group NFTs in a collectible category in the catalog when filtering by categories

- [x] Add a label (like the tooltip) to the Scene Catalog for each item with the name of the item (check original Builder behaviour)

- [x] "Move Camera Up and Down" is not included in controls scheme panel with key shortcut "N" ( X for down, space for Up)
